server:
  port: 11001
spring:
  application:
    name: sfnotice
  cloud:
    service-registry:
      auto-registration:
        enabled: true
#注册中心
eureka:
  username: lyhace
  password: 123456
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://${eureka.username}:${eureka.password}@eureka01:10011/eureka/,http://${eureka.username}:${eureka.password}@eureka02:10012/eureka/
    #配置开启健康检查，并按需配置续约更新时间和到期时间
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10 #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30 #续约到期时间（默认90秒）

#增加健康检查监控
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: ["health","info","shutdown"]
  endpoint:
    health:
      show-details: always
      shutdown:
        enabled: true
info:
  name: ${spring.application.name}
  description: SF通知服务接收端
  version: V1.0.0