server:
  port: 11002
spring:
  application:
    name: jdnotice
  cloud:
    service-registry:
      auto-registration:
        enabled: true
#注册中心
eureka:
  username: lyhace
  password: 123456
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://${eureka.username}:${eureka.password}@eureka01:10011/eureka/,http://${eureka.username}:${eureka.password}@eureka02:10012/eureka/
    #配置开启健康检查，并按需配置续约更新时间和到期时间
    healthcheck:
      enabled: true
    #作为Eureka Client客户端，是否从Eureka Server获取注册信息，这里设置为true，表示需要从Eureka Server定期获取注册了的Provider实例清单。
    fetch-registry: true
    #作为Eureka Client客户端，从Eureka服务器端获取注册信息的间隔时间，单位为秒，默认为30秒。
    registry-fetch-interval-seconds: 5
    #更新实例信息的变化到Eureka服务端的间隔时间，单位为秒，默认为30秒。
    instance-info-replication-interval-seconds: 10
  instance:
    #该服务实例在注册中心的唯一实例ID
    instance-id: ${spring.application.name}-${spring.cloud.client.ipaddress}-${server.port}
    lease-renewal-interval-in-seconds: 10 #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30 #续约到期时间（默认90秒）
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #熔断器的超时时长默认1秒，最常修改的参数
          timeout:
            enabled: false # 为false则超时控制有ribbon控制，为true则hystrix超时和ribbon超时都是用，但是谁小谁生效，默认为true

ribbon:
  MaxAutoRetries: 1 #同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 500  #连接建立的超时时长，默认1秒
  ReadTimeout: 500 #处理请求的超时时间，默认为1秒
  #Ribbon默认GET请求不论是连接失败还是处理失败都会重试，而对于非GET请求只对连接失败进行重试
  #配置Hystrix的timeoutInMillisecond要大于Ribbon的 ( ConnectTimeout + ReadTimeout ) × 2。目的就是保证在熔断之前完成远程调用(包括Ribbon的重试时间)。

#增加健康检查监控
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: ["health","info","shutdown"]
  endpoint:
    health:
      show-details: always
      shutdown:
        enabled: true
info:
  name: ${spring.application.name}
  description: JD通知服务接收端
  version: V1.0.0